# Generated by Django 3.1.6 on 2021-06-30 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalnoofrides', models.IntegerField(blank=True, null=True)),
                ('totalrevenue', models.IntegerField(blank=True, null=True)),
                ('fromtotalrides', models.IntegerField(blank=True, null=True)),
                ('noservicetypes', models.IntegerField(blank=True, null=True)),
                ('dashboardtotalrides', models.IntegerField(blank=True, null=True)),
                ('cancelledcount', models.IntegerField(blank=True, null=True)),
                ('providercancelledcount', models.IntegerField(blank=True, null=True)),
                ('nooffleet', models.IntegerField(blank=True, null=True)),
                ('noscheduledrides', models.IntegerField(blank=True, null=True)),
                ('totalusers', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
