# Generated by Django 3.1.6 on 2021-06-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabroozadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='cancelledpercentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='forpercentrides',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
