# Generated by Django 3.1.6 on 2021-07-01 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabroozadmin', '0004_auto_20210701_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='providers',
            name='action',
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overallearnings', models.CharField(blank=True, max_length=255, null=True)),
                ('overallcommission', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cabroozadmin.user')),
            ],
        ),
        migrations.CreateModel(
            name='FleetOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile', models.CharField(blank=True, max_length=25, null=True)),
                ('request', models.CharField(blank=True, max_length=255, null=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('action', models.CharField(blank=True, max_length=65, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cabroozadmin.user')),
            ],
        ),
        migrations.CreateModel(
            name='Dispatcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatchername', models.CharField(blank=True, max_length=255, null=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('action', models.CharField(blank=True, max_length=65, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cabroozadmin.user')),
            ],
        ),
    ]
