# Generated by Django 3.1.6 on 2021-07-01 13:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cabroozadmin', '0005_auto_20210701_1657'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Providers',
            new_name='Provider',
        ),
        migrations.RenameModel(
            old_name='RecentRides',
            new_name='RecentRide',
        ),
    ]
