# Generated by Django 3.1.6 on 2021-07-01 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabroozadmin', '0006_auto_20210701_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleetowner',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
