# Generated by Django 3.1.6 on 2021-07-02 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabroozadmin', '0007_fleetowner_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestHistory',
            fields=[
                ('bookingid', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('providername', models.CharField(blank=True, max_length=255, null=True)),
                ('time', models.DateField(auto_now_add=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('Amount', models.IntegerField(blank=True, null=True)),
                ('paymentmode', models.CharField(blank=True, max_length=255, null=True)),
                ('paymentstatus', models.CharField(max_length=255, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cabroozadmin.user')),
            ],
        ),
    ]
