# Generated by Django 3.1.6 on 2021-07-02 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabroozadmin', '0008_requesthistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicename', models.CharField(blank=True, max_length=255, null=True)),
                ('providername', models.CharField(blank=True, max_length=255, null=True)),
                ('capacity', models.CharField(blank=True, max_length=255, null=True)),
                ('baseprice', models.IntegerField(blank=True, null=True)),
                ('basediscount', models.IntegerField(blank=True, null=True)),
                ('timeprice', models.IntegerField(blank=True, null=True)),
                ('pricecalculations', models.IntegerField(blank=True, null=True)),
                ('serviceimage', models.ImageField(blank=True, null=True, upload_to='')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cabroozadmin.user')),
            ],
        ),
    ]
