# Generated by Django 3.1.6 on 2021-07-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabroozadmin', '0011_driverdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverdetails',
            name='approved',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='driverdetails',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='driverdetails',
            name='time',
            field=models.DateField(auto_now_add=True, default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driverdetails',
            name='wallet',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
