# Generated by Django 3.1.6 on 2021-07-03 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabroozadmin', '0012_auto_20210703_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverdetails',
            name='approved',
        ),
    ]
