# Generated by Django 3.1.6 on 2021-07-03 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabroozadmin', '0013_remove_driverdetails_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverdetails',
            old_name='cnicback',
            new_name='drivercnicback',
        ),
        migrations.RenameField(
            model_name='driverdetails',
            old_name='cnicfront',
            new_name='drivercnicfront',
        ),
        migrations.RenameField(
            model_name='driverdetails',
            old_name='email',
            new_name='driveremail',
        ),
        migrations.RenameField(
            model_name='driverdetails',
            old_name='gender',
            new_name='drivergender',
        ),
        migrations.RenameField(
            model_name='driverdetails',
            old_name='name',
            new_name='drivername',
        ),
        migrations.RenameField(
            model_name='driverdetails',
            old_name='phone',
            new_name='driverphone',
        ),
        migrations.RenameField(
            model_name='driverdetails',
            old_name='photo',
            new_name='driverphoto',
        ),
    ]
