# Generated by Django 3.1.6 on 2021-07-03 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabroozadmin', '0016_driverdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverdetails',
            old_name='drivercnicback',
            new_name='cnicback',
        ),
        migrations.RenameField(
            model_name='driverdetails',
            old_name='drivercnicfront',
            new_name='cnicfront',
        ),
        migrations.RenameField(
            model_name='driverdetails',
            old_name='driveremail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='driverdetails',
            old_name='drivergender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='driverdetails',
            old_name='drivername',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='driverdetails',
            old_name='driverphone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='driverdetails',
            old_name='driverphoto',
            new_name='photo',
        ),
    ]
