# Generated by Django 3.1.6 on 2021-07-03 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabroozadmin', '0017_auto_20210703_2132'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DriverDetails',
        ),
    ]
