# Generated by Django 3.1.6 on 2021-07-05 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabroozadmin', '0019_driverdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverdetails',
            old_name='name',
            new_name='drivername',
        ),
    ]
