# Generated by Django 3.1.6 on 2021-07-05 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabroozadmin', '0020_auto_20210705_1653'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DriverDetails',
        ),
    ]
