# Generated by Django 3.1.6 on 2021-07-05 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabroozadmin', '0022_driverdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverdetails',
            old_name='status',
            new_name='statuses',
        ),
    ]
